/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        C_Ferramentas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        C_Amigos = new javax.swing.JButton();
        C_Empréstimo = new javax.swing.JButton();
        c_lista = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Saida = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 100, 100));
        jLabel1.setText("BEM VINDO!");

        C_Ferramentas.setBackground(new java.awt.Color(0, 100, 70));
        C_Ferramentas.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        C_Ferramentas.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        C_Ferramentas.setText("Cadastrar ferramentas");
        C_Ferramentas.setToolTipText("");
        C_Ferramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_FerramentasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel2.setText("O que você gostaria de executar?");

        C_Amigos.setBackground(new java.awt.Color(0, 100, 70));
        C_Amigos.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        C_Amigos.setForeground(new java.awt.Color(255, 255, 255));
        C_Amigos.setText("Cadastrar amigos");
        C_Amigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_AmigosActionPerformed(evt);
            }
        });

        C_Empréstimo.setBackground(new java.awt.Color(0, 100, 70));
        C_Empréstimo.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        C_Empréstimo.setForeground(new java.awt.Color(255, 255, 255));
        C_Empréstimo.setText("Realizar empréstimo");
        C_Empréstimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_EmpréstimoActionPerformed(evt);
            }
        });

        c_lista.setBackground(new java.awt.Color(0, 100, 70));
        c_lista.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        c_lista.setForeground(new java.awt.Color(255, 255, 255));
        c_lista.setText("Lista de empréstimos");
        c_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_listaActionPerformed(evt);
            }
        });

        Saida.setText("Sair");
        Saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaActionPerformed(evt);
            }
        });
        jMenuBar1.add(Saida);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(C_Empréstimo, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(c_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(C_Ferramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(C_Amigos, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_Ferramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_Amigos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_Empréstimo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void C_FerramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_FerramentasActionPerformed
        this.dispose();
        CadastroFerramenta objeto = new CadastroFerramenta();
        objeto.setVisible(true);
    }//GEN-LAST:event_C_FerramentasActionPerformed

    private void C_EmpréstimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_EmpréstimoActionPerformed
        this.dispose();
        RealizarEmprestimo objeto3 = new RealizarEmprestimo();
        objeto3.setVisible(true);
    }//GEN-LAST:event_C_EmpréstimoActionPerformed

    private void SaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SaidaActionPerformed

    private void C_AmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_AmigosActionPerformed
        this.dispose();
        CadastroAmigo objeto2 = new CadastroAmigo();
        objeto2.setVisible(true);
    }//GEN-LAST:event_C_AmigosActionPerformed

    private void c_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_listaActionPerformed
        this.dispose();
        ListaEmprestimo objeto4 = new ListaEmprestimo();
        objeto4.setVisible(true);
    }//GEN-LAST:event_c_listaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C_Amigos;
    private javax.swing.JButton C_Empréstimo;
    private javax.swing.JButton C_Ferramentas;
    private javax.swing.JMenu Saida;
    private javax.swing.JButton c_lista;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
